## Reading Csv File

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
df = pd.read_csv('lec25.csv')

In [3]:
df

q  r  s  t   apple
0  2  3  4  5    pear
1  a  s  d  f  rabbit
2  5  2  5  7     dog

In [5]:
df = pd.read_csv('lec25.csv',header = None)

In [6]:
df

0  1  2  3       4
0  q  r  s  t   apple
1  2  3  4  5    pear
2  a  s  d  f  rabbit
3  5  2  5  7     dog

In [7]:
df = pd.read_table('lec25.csv',sep = ',',header = None)
df

0  1  2  3       4
0  q  r  s  t   apple
1  2  3  4  5    pear
2  a  s  d  f  rabbit
3  5  2  5  7     dog

In [10]:
pd.read_csv('lec25.csv',header = None,nrows =2)  # 限定行数

0  1  2  3      4
0  q  r  s  t  apple
1  2  3  4  5   pear

In [11]:
df

0  1  2  3       4
0  q  r  s  t   apple
1  2  3  4  5    pear
2  a  s  d  f  rabbit
3  5  2  5  7     dog

In [12]:
df.to_csv('mytextdata_out.csv')  

In [13]:
import sys

In [18]:
df.to_csv(sys.stdout,sep = ' ')

 0 1 2 3 4
0 q r s t apple
1 2 3 4 5 pear
2 a s d f rabbit
3 5 2 5 7 dog


In [19]:
df.to_csv(sys.stdout,sep = '?')

?0?1?2?3?4
0?q?r?s?t?apple
1?2?3?4?5?pear
2?a?s?d?f?rabbit
3?5?2?5?7?dog


In [23]:
df.to_csv(sys.stdout,columns =[0,1,2] ,sep = ' ')

 0 1 2
0 q r s
1 2 3 4
2 a s d
3 5 2 5


In [24]:
url = 'https://docs.python.org/3/library/csv.html'

##  Json with Python

In [25]:
json_obj = """
{   "zoo_animal": "Lion",
    "food": ["Meat", "Veggies", "Honey"],
    "fur": "Golden",
    "clothes": null, 
    "diet": [{"zoo_animal": "Gazelle", "food":"grass", "fur": "Brown"}]
}
"""

In [26]:
import json

In [27]:
data = json.loads(json_obj)  # str to json
data

{'clothes': None,
 'diet': [{'food': 'grass', 'fur': 'Brown', 'zoo_animal': 'Gazelle'}],
 'food': ['Meat', 'Veggies', 'Honey'],
 'fur': 'Golden',
 'zoo_animal': 'Lion'}

In [28]:
json.dumps(data)  # json to str

'{"diet": [{"fur": "Brown", "zoo_animal": "Gazelle", "food": "grass"}], "fur": "Golden", "clothes": null, "zoo_animal": "Lion", "food": ["Meat", "Veggies", "Honey"]}'

In [29]:
df = DataFrame(data['diet'])

In [30]:
df

food    fur zoo_animal
0  grass  Brown    Gazelle

## HTML with Python

In [31]:
from pandas import read_html

In [4]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'

In [2]:
from bs4 import BeautifulSoup
import html5lib

In [22]:
df_list = pd.io.html.read_html(url)

In [13]:
df = DataFrame(df_list[0])

In [16]:
df.head(5)

Bank Name                City  ST  \
0    The Farmers and Merchants State Bank of Argonia             Argonia  KS   
1                                Fayette County Bank          Saint Elmo  IL   
2  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee  WI   
3                                     First NBC Bank         New Orleans  LA   
4                                      Proficio Bank  Cottonwood Heights  UT   

    CERT                Acquiring Institution      Closing Date  \
0  17719                          Conway Bank  October 13, 2017   
1   1802            United Fidelity Bank, fsb      May 26, 2017   
2  30003  First-Citizens Bank & Trust Company       May 5, 2017   
3  58302                         Whitney Bank    April 28, 2017   
4  35495                    Cache Valley Bank     March 3, 2017   

       Updated Date  
0  October 20, 2017  
1     July 26, 2017  
2     July 26, 2017  
3     July 26, 2017  
4      May 18, 2017

In [25]:
df.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

In [26]:
df.columns.values

array(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'], dtype=object)

In [34]:
# same as  pd.io.html.read_html(url)
df2_list = pd.read_html(url)

## Excel files with Python

In [43]:
xlsfile = pd.ExcelFile('Lec_28_test.xlsx')
xlsfile

In [41]:
df = xlsfile.parse('Sheet1')

In [42]:
df

This is a test  Unnamed: 1  Unnamed: 2
0              23        6678         456
1             234         678         456
2             234           7         345
3              34          56         234
4               5         456        4365

## Merge

In [45]:
df1 = DataFrame({'key':['x','z','y','z','x','x'],'data_set_1':np.arange(6)})
df1

data_set_1 key
0           0   x
1           1   z
2           2   y
3           3   z
4           4   x
5           5   x

In [79]:
df2 = DataFrame({'key':['q','y','z'],'data_set_2':[4,5,6]})
df2

data_set_2 key
0           4   q
1           5   y
2           6   z

In [80]:
pd.merge(df1,df2)  #  df1里有2个z,都匹配了df2中的z

data_set_1 key  data_set_2
0           1   z           6
1           3   z           6
2           2   y           5

In [81]:
pd.merge(df1,df2,on = 'key')   #  on :在哪一列merge

data_set_1 key  data_set_2
0           1   z           6
1           3   z           6
2           2   y           5

In [82]:
#  how选择用哪个df作为主df(像sql的left right join)
pd.merge(df1,df2,how = 'left')

data_set_1 key  data_set_2
0           0   x         NaN
1           1   z         6.0
2           2   y         5.0
3           3   z         6.0
4           4   x         NaN
5           5   x         NaN

In [83]:
pd.merge(df1,df2,how = 'right')

data_set_1 key  data_set_2
0         1.0   z           6
1         3.0   z           6
2         2.0   y           5
3         NaN   q           4

In [84]:
pd.merge(df1,df2,how = 'outer')  # 'outer'

data_set_1 key  data_set_2
0         0.0   x         NaN
1         4.0   x         NaN
2         5.0   x         NaN
3         1.0   z         6.0
4         3.0   z         6.0
5         2.0   y         5.0
6         NaN   q         4.0

In [85]:
df3 = DataFrame({'key':['x','x','x','y','z','z'],'data_set_3':range(6)})
df3

data_set_3 key
0           0   x
1           1   x
2           2   x
3           3   y
4           4   z
5           5   z

In [87]:
df4 = DataFrame({'key':['y','y','x','x','z'],'data_set_4':range(5)})
df4

data_set_4 key
0           0   y
1           1   y
2           2   x
3           3   x
4           4   z

In [92]:
pd.merge(df3,df4)

data_set_3 key  data_set_4
0           0   x           2
1           0   x           3
2           1   x           2
3           1   x           3
4           2   x           2
5           2   x           3
6           3   y           0
7           3   y           1
8           4   z           4
9           5   z           4

In [96]:
df_left = DataFrame({'key1':['SF','SF','LA'],
                                  'key2':['one','two','one'],
                                  'left_data':[10,20,30]})

In [102]:
df_right = DataFrame({'key1':['SF','SF','LA','LA'],
                                  'key2':['one','one','one','two'],
                                  'right_data':[40,50,60,70]})

In [97]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [103]:
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [105]:
pd.merge(df_left,df_right,on = ['key1','key2'],how = 'outer')

key1 key2  left_data  right_data
0   SF  one       10.0        40.0
1   SF  one       10.0        50.0
2   SF  two       20.0         NaN
3   LA  one       30.0        60.0
4   LA  two        NaN        70.0

In [106]:
pd.merge(df_left,df_right, on = 'key1')  #key2_x 和key2_y是pandas自动生成,因只用了key1

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

In [108]:
pd.merge(df_left,df_right, on = 'key1',suffixes=('_lefty','_righty'))  #suffixes 改变key2后缀名

key1 key2_lefty  left_data key2_righty  right_data
0   SF        one         10         one          40
1   SF        one         10         one          50
2   SF        two         20         one          40
3   SF        two         20         one          50
4   LA        one         30         one          60
5   LA        one         30         two          70

In [ ]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.merge.html'

## Merge on Index

In [109]:
dfl = DataFrame({'key':['x','y','z','x','y'],'data':range(5)})
dfr = DataFrame({'froup_data':[10,20]},index = ['x','y'])

In [110]:
dfl

data key
0     0   x
1     1   y
2     2   z
3     3   x
4     4   y

In [111]:
dfr

froup_data
x          10
y          20

In [114]:
pd.merge(dfl,dfr,left_on = 'key',right_index = True)

data key  froup_data
0     0   x          10
3     3   x          10
1     1   y          20
4     4   y          20

In [116]:
df_l_hr = DataFrame({'key1':['SF','SF','SF','LA','LA'],
                                    'key2':[10,20,30,20,30],
                                    'data_Set':np.arange(5.)})

In [117]:
df_l_hr

data_Set key1  key2
0       0.0   SF    10
1       1.0   SF    20
2       2.0   SF    30
3       3.0   LA    20
4       4.0   LA    30

In [118]:
df_r_hr = DataFrame(np.arange(10).reshape(5,2),
                                   index = [['LA','LA','SF','SF','SF'],[20,10,10,10,20]],
                                   columns = ['col_1','col_2'])
df_r_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [122]:
pd.merge(df_l_hr,df_r_hr,left_on = ['key1','key2'],right_index =True)

data_Set key1  key2  col_1  col_2
0       0.0   SF    10      4      5
0       0.0   SF    10      6      7
1       1.0   SF    20      8      9
3       3.0   LA    20      0      1

In [123]:
dfl.join(dfr)

data key  froup_data
0     0   x         NaN
1     1   y         NaN
2     2   z         NaN
3     3   x         NaN
4     4   y         NaN

## Concatenate

In [124]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
np.concatenate([arr1,arr1],axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [128]:
np.concatenate([arr1,arr1],axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
ser1 = Series([0,1,2],index = ['T','U','V'])
ser2 = Series([3,4],index = ['x','y'])

In [130]:
ser1

T    0
U    1
V    2
dtype: int64

In [131]:
ser2

x    3
y    4
dtype: int64

In [134]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
x    3
y    4
dtype: int64

In [135]:
pd.concat([ser1,ser2],axis = 1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
x  NaN  3.0
y  NaN  4.0

In [137]:
pd.concat([ser1,ser2],keys = ['cat1','cat2'],axis =1)

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
x   NaN   3.0
y   NaN   4.0

In [138]:
df1 = DataFrame(np.random.randn(4,3),columns = ['X','Y','Z'])
df2 = DataFrame(np.random.randn(3,3),columns = ['Y','Q','Z'])
df1

X         Y         Z
0  0.370435 -0.759644  0.610468
1 -0.552989 -1.519503 -0.917420
2  0.751871 -0.813351  0.972478
3 -0.360554  0.566997 -0.910480

In [139]:
df2

Y         Q         Z
0 -0.165559 -0.629110  0.241156
1 -0.224741 -0.687821 -0.639548
2  0.885342  1.537691 -1.486824

In [141]:
pd.concat([df1,df2])  # 默认保留各自的index

Q         X         Y         Z
0       NaN  0.370435 -0.759644  0.610468
1       NaN -0.552989 -1.519503 -0.917420
2       NaN  0.751871 -0.813351  0.972478
3       NaN -0.360554  0.566997 -0.910480
0 -0.629110       NaN -0.165559  0.241156
1 -0.687821       NaN -0.224741 -0.639548
2  1.537691       NaN  0.885342 -1.486824

In [142]:
pd.concat([df1,df2],ignore_index=True)  # 不保留本身的index

Q         X         Y         Z
0       NaN  0.370435 -0.759644  0.610468
1       NaN -0.552989 -1.519503 -0.917420
2       NaN  0.751871 -0.813351  0.972478
3       NaN -0.360554  0.566997 -0.910480
4 -0.629110       NaN -0.165559  0.241156
5 -0.687821       NaN -0.224741 -0.639548
6  1.537691       NaN  0.885342 -1.486824

In [143]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'

## Combine DataFrames

In [144]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],index = ['Q','R','S','T','U','V'])
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [145]:
ser2 = Series(np.arange(len(ser1)),dtype = np.float64,index =  ['Q','R','S','T','U','V'])
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [146]:
Series(np.where(pd.isnull(ser1),ser2,ser1),index = ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [149]:
ser1.combine_first(ser2)  # combine_first和上面作用一样

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [150]:
df_odds = DataFrame({'x':[1.,np.nan,3.,np.nan],'y':[np.nan,5.,np.nan,7.],'z':[np.nan,9.,np.nan,11]})
df_odds

x    y     z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [151]:
df_evens = DataFrame({'x':[2.,4.,np.nan,6.,8.],'y':[np.nan,10.,12.,14.,16.]})
df_evens

x     y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [152]:
df_odds.combine_first(df_evens)

x     y     z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

## Reshaping

In [154]:
# 用pd.Index 可以在后面给index命名
df1 = DataFrame(np.arange(8).reshape(2,4),
                             index = pd.Index(['LA','SF'],name = 'city'),
                             columns = pd.Index(['A','B','C','D'],name = 'letter'))
df1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [157]:
df2 = df1.stack()

In [160]:
df2

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int32

In [161]:
df2.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [162]:
df2.unstack('letter')

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [163]:
df2.unstack('city')

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [164]:
ser1 = Series([0,1,2],index = ['Q','X','Y'])
ser2 = Series([4,5,6],index = ['X','Y','Z'])

In [165]:
df = pd.concat([ser1,ser2],keys=['Alpha','Beta'])

In [166]:
df

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [167]:
df.unstack()

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [168]:
df.unstack().stack()

Alpha  Q    0.0
       X    1.0
       Y    2.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [171]:
df1 = df.unstack()
df1

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [173]:
df1.stack(dropna=False)  # 保留nan

Alpha  Q    0.0
       X    1.0
       Y    2.0
       Z    NaN
Beta   Q    NaN
       X    4.0
       Y    5.0
       Z    6.0
dtype: float64

## Pivoting

In [174]:
#pivot tables

In [175]:
#what am i seeking?

In [177]:
# import pandas testing utility
import pandas.util.testing as tm;tm.N = 3
#Create a unpivoted function
def unpivot(frame):
    N,K = frame.shape
    
    data = {'value': frame.values.ravel('F'),
                 'variable':np.asarray(frame.columns).repeat(N),
                 'date':np.tile(np.asarray(frame.index),K)
           }
    return DataFrame(data,columns=['date','variable','value'])

#Set the DataFrame we'll be using
df = unpivot(tm.makeTimeDataFrame())

In [182]:
df 

date variable     value
0  2000-01-03        A  0.021925
1  2000-01-04        A -1.004286
2  2000-01-05        A -0.489703
3  2000-01-03        B -1.805443
4  2000-01-04        B -0.835036
5  2000-01-05        B  0.888795
6  2000-01-03        C  0.942212
7  2000-01-04        C  1.355257
8  2000-01-05        C  0.232772
9  2000-01-03        D -1.252362
10 2000-01-04        D  0.330243
11 2000-01-05        D  0.744529

In [183]:
df_piv = df.pivot('date','variable','value')

In [184]:
df_piv

variable           A         B         C         D
date                                              
2000-01-03  0.021925 -1.805443  0.942212 -1.252362
2000-01-04 -1.004286 -0.835036  1.355257  0.330243
2000-01-05 -0.489703  0.888795  0.232772  0.744529

## Duplicates In DataFrames

In [185]:
df = DataFrame({'key1':['A']*2 + ['B']*3,'key2':[2,2,2,3,3]})
df

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [187]:
df.duplicated()  # 是否有重复行

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [188]:
df.drop_duplicates() 

key1  key2
0    A     2
2    B     2
3    B     3

In [194]:
df.drop_duplicates(['key1'])  

key1  key2
0    A     2
2    B     2

In [196]:
df.drop_duplicates('key2')

key1  key2
0    A     2
3    B     3

In [195]:
df.drop_duplicates(['key1','key2'])

key1  key2
0    A     2
2    B     2
3    B     3

In [200]:
df.drop_duplicates('key1',keep='last')  # keep='last'  保留最后一次出现的

key1  key2
1    A     2
4    B     3

In [199]:
df.drop_duplicates('key2',keep='last')

key1  key2
2    B     2
4    B     3

## Mapping

In [201]:
df = DataFrame({'city':['Alma','Brian Head','Fox Park'],'altitude':[3158,3000,2762]})
df

altitude        city
0      3158        Alma
1      3000  Brian Head
2      2762    Fox Park

In [202]:
state_map = {'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}

In [203]:
df['state'] = df['city'].map(state_map)

In [204]:
df

altitude        city     state
0      3158        Alma  Colorado
1      3000  Brian Head      Utah
2      2762    Fox Park   Wyoming

## Replace Values

In [207]:
ser1 = Series([1,2,3,4,1,2,3,4])
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [208]:
ser1.replace(1,np.nan)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [210]:
ser1.replace([1,4],[100,400])

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [212]:
ser1.replace({3:300})  #用字典形式替换

0      1
1      2
2    300
3      4
4      1
5      2
6    300
7      4
dtype: int64

## Rename Index

In [214]:
df = DataFrame(np.arange(12).reshape(3,4),index = ['NY','LA','SF'],columns = ['A','B','C','D'])
df

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [215]:
df.index.map(str.lower)

array(['ny', 'la', 'sf'], dtype=object)

In [217]:
df.columns.map(str.lower)

array(['a', 'b', 'c', 'd'], dtype=object)

In [222]:
df.rename(index = str.title,columns = str.lower)  #  str.title 首字母大写,.capitalize()一样

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [220]:
df.rename(index = {'NY':'New York','LA':'Los Angels'},columns = {'A':'Alpha'})

Alpha  B   C   D
New York        0  1   2   3
Los Angels      4  5   6   7
SF              8  9  10  11

## Binning :seperate data into different bins

In [226]:
years = [1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]

In [234]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]  #  明确要bin的数量

In [235]:
decade_cat = pd.cut(years,decade_bins)

In [236]:
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, object): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [237]:
decade_cat.categories

Index(['(1960, 1970]', '(1970, 1980]', '(1980, 1990]', '(1990, 2000]',
       '(2000, 2010]', '(2010, 2020]'],
      dtype='object')

In [238]:
pd.value_counts(decade_cat)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [239]:
pd.cut(years,2,precision=1)

[(1969, 1992], (1969, 1992], (1969, 1992], (1992, 2015], (1992, 2015], ..., (1969, 1992], (1969, 1992], (1992, 2015], (1992, 2015], (1992, 2015]]
Length: 11
Categories (2, object): [(1969, 1992] < (1992, 2015]]

In [240]:
pd.cut(years,2,precision=1).categories  # 2表示只分2部分

Index(['(1969, 1992]', '(1992, 2015]'], dtype='object')

##  Outliers

In [242]:
np.random.seed(12345)

In [277]:
df = DataFrame(np.random.randn(1000,4))

In [278]:
df.head()

0         1         2         3
0  1.150765 -0.997174  0.046486 -0.610441
1 -0.394982  1.199915 -0.451814 -0.155385
2 -0.153514  0.011194 -0.050555  0.420211
3  1.190981  1.561488 -1.132925  0.097083
4 -1.031573 -0.044618 -0.218153  0.772942

In [279]:
df.tail()

0         1         2         3
995 -0.805171  0.976343  0.859475  0.203516
996 -0.064420  0.487940  1.353146  0.291152
997 -0.051474  1.353153  1.066038  1.260350
998 -0.144072 -1.074131 -0.245138  1.474357
999 -0.741705 -0.462397 -0.419776  0.592210

In [280]:
df.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.020880     0.001643    -0.019453    -0.026122
std       0.980023     1.025441     0.995088     0.960486
min      -3.108915    -3.645860    -3.481593    -3.194414
25%      -0.697479    -0.697678    -0.694020    -0.700987
50%      -0.005279     0.031774    -0.014728    -0.038483
75%       0.618116     0.690065     0.651287     0.649747
max       2.859053     3.189940     3.525865     3.023720

In [281]:
col = df[0]

In [282]:
col.head()

0    1.150765
1   -0.394982
2   -0.153514
3    1.190981
4   -1.031573
Name: 0, dtype: float64

In [283]:
col[np.abs(col)>3]

396   -3.108915
Name: 0, dtype: float64

In [284]:
col[col.abs()>3]

396   -3.108915
Name: 0, dtype: float64

In [285]:
df[(np.abs(df)>3).any(1)]

0         1         2         3
46  -0.658090 -0.207434  3.525865  0.283070
67   0.599947 -3.645860  0.255475 -0.549574
289 -1.559625  0.336788 -3.333767 -1.240685
371 -1.116332 -3.018842 -0.298748  0.406954
396 -3.108915  1.117755 -0.152780 -0.340173
526  1.188742 -3.183867  1.050471 -1.042736
573 -2.214074 -3.140963 -1.509976 -0.389818
738 -0.088202  1.090038 -0.848098 -3.194414
768  0.474358  0.003349 -0.011807  3.023720
797  2.368010  0.452649 -3.481593  0.789944
966  0.164293  3.082067 -0.516982  0.251909
994 -0.843849  3.189940  0.070978  0.516982

In [288]:
df[np.abs(df)>3] =np.sign(df)*3  # np.sign() 返回1或-1 (大于0 返回1,小于0返回-1)

In [289]:
df.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.020772     0.002361    -0.019163    -0.025951
std       0.979685     1.021487     0.990725     0.959788
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.697479    -0.697678    -0.694020    -0.700987
50%      -0.005279     0.031774    -0.014728    -0.038483
75%       0.618116     0.690065     0.651287     0.649747
max       2.859053     3.000000     3.000000     3.000000

## Permutation 

In [305]:
#置换；排列（方式）；组合（方式）

In [291]:
df = DataFrame(np.arange(16).reshape(4,4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [295]:
blender = np.random.permutation(4)
blender

array([0, 2, 3, 1])

In [296]:
df.take(blender)  # 使用blender的顺序作为index顺序

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [297]:
box = np.array([1,2,3])
box

array([1, 2, 3])

In [302]:
shaker = np.random.randint(0,len(box),size=10)
shaker

array([0, 2, 0, 1, 2, 0, 2, 0, 2, 0])

In [304]:
# 按照shaker的顺序去box里面取出相应index对应的数(就像在箱子里取纸条一样)
# s因为haker是随机生成的
hand_grabs = box.take(shaker)  
hand_grabs

array([1, 3, 1, 2, 3, 1, 3, 1, 3, 1])